name: SignalK Plugin CI

on:
  push:
  pull_request:

jobs:
  test:
    # uses: SignalK/signalk-server/.github/workflows/plugin-ci.yml@master
    uses: jaffadog/signalk-server/.github/workflows/plugin-ci.yml@feat/separate-build-node-version
    # with:
      # build-command: "npm run build"
